### ISSUE TITLE
Trade functionality

### ISSUE THREAD

**Issue by Ahimal14** [genfanad/genfanad-public-bugtracker#16]
Trade window has no add all or add X, and only allows the user to see the top 24 items not the full 30 in your inventory

**Comment by rstan122** [comment]
Trading is odd.  You have the option to add all or add X if the item is stackable and you right click it.

You get a warning if you try to add any stackable item after 15 that says "You can't trade more than 15 items at a time"..
which is not true.  Really, you can't add any STACKABLE items after the 15 visible.  You can trade more than 15, but the stackable items need to be visible.  Below is an example where I traded all 30 inventory items
![image](https://user-images.githubusercontent.com/4697709/193279947-727f693a-4d21-41c2-b465-de889f025767.png)

When completed, the trade then fails with a chat message because the other party did not have 30 free slots available.

**Comment by rstan122** [comment]
Another note on trade functionality, if you close the trade dialog window, the trade is not actually ended.  It will still be visible for the other party.  If the other party makes a change, such as adding an item, the window reappears.  It is ended if either party moves.
